language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer selfupdate
  - composer install
  - vendor/bin/phpcs --config-set installed_paths /home/travis/build/loadsys/loadsys_codesniffer/vendor/cakephp/cakephp-codesniffer

script:
  - vendor/bin/phpunit

notifications:
  email: false
