language: php

php:
  - 5.6

before_script:
  - composer selfupdate
  - composer install
  - vendor/bin/phpcs --config-set installed_paths vendor/cakephp/cakephp-codesniffer

script:
  - vendor/bin/phpunit

notifications:
  email: false
