sudo: false

language: php

php:
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer selfupdate
  - composer install
  - vendor/bin/phpcs --config-set installed_paths vendor/cakephp/cakephp-codesniffer

script:
  - vendor/bin/phpcs -ps --standard=snifftests/sniff_class_rules.xml Loadsys/
  - vendor/bin/phpunit

notifications:
  email: false
