language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mv ../loadsys-codesniffer ../loadsys_codesniffer && cd ../loadsys_codesniffer
  - pear install PHP_CodeSniffer
  - phpenv rehash

script:
  - phpunit

notifications:
  email: false
